namespace FH.LanguageComboTool.Wpf;

public sealed class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Languages =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["CHS"] = CreateChinese(),
            ["EN"] = CreateEnglish()
        };

    public string CurrentLanguage { get; private set; } = "CHS";

    public IReadOnlyList<UiLanguage> SupportedLanguages { get; } =
    [
        new("CHS", "简体中文"),
        new("EN", "English")
    ];

    public void SetLanguage(string? language)
    {
        CurrentLanguage = !string.IsNullOrWhiteSpace(language) && Languages.ContainsKey(language)
            ? language.ToUpperInvariant()
            : "CHS";
    }

    public string T(string key)
    {
        if (Languages[CurrentLanguage].TryGetValue(key, out var value))
            return value;
        if (Languages["CHS"].TryGetValue(key, out value))
            return value;
        return key;
    }

    public string Format(string key, params object?[] args) => string.Format(T(key), args);

    public string LanguageName(string code) => T($"Language_{code.ToUpperInvariant()}");

    private static IReadOnlyDictionary<string, string> CreateChinese() => new Dictionary<string, string>
    {
        ["AppName"] = "FH 语言组合工具",
        ["NavHome"] = "主页",
        ["NavBackups"] = "备份",
        ["NavSettings"] = "设置",
        ["NavAbout"] = "关于",
        ["LanguageTitle"] = "界面语言",
        ["LanguageIntro"] = "请选择界面语言。之后可在设置中随时更改。",
        ["Continue"] = "继续",
        ["DisclaimerTitle"] = "使用前确认",
        ["DisclaimerIntro"] = "本工具会修改本地 Forza Horizon 语言资源文件。继续前请阅读并确认以下事项。",
        ["Disclaimer1"] = "本工具与 Playground Games、Microsoft、Xbox 或 Turn 10 无官方关联。",
        ["Disclaimer2"] = "工具会修改 StringTables 语言文件，并在每次操作前自动创建备份。",
        ["Disclaimer3"] = "游戏更新或 Steam 文件验证可能覆盖修改结果，届时需要重新应用配置。",
        ["Disclaimer4"] = "请自行承担本地文件修改带来的风险，并确保游戏未在运行。",
        ["Accept"] = "接受并继续",
        ["Game"] = "游戏",
        ["InstalledGames"] = "已安装游戏",
        ["Detect"] = "检测",
        ["NoGameSelected"] = "尚未选择游戏。",
        ["ManualDirectory"] = "手动添加目录",
        ["ManualPathHint"] = "选择游戏根目录",
        ["Browse"] = "浏览",
        ["Validate"] = "验证目录",
        ["Backups"] = "备份与恢复",
        ["BackupsDescription"] = "选择一个有效备份，将游戏语言资源恢复到修改前状态。",
        ["RestoreSelected"] = "恢复所选备份",
        ["Settings"] = "设置",
        ["InterfaceLanguage"] = "界面语言",
        ["SettingsDescription"] = "可在此切换界面语言或重置首次启动状态。",
        ["ResetFirstRun"] = "重置首次启动提示",
        ["LanguageCombo"] = "语言配置",
        ["LanguageComboIntro"] = "为游戏分别选择语音语言与文字语言。",
        ["LanguageComboDescription"] = "工具会先备份原始语音包，再将文字语言包覆盖到目标语音包。",
        ["VoiceLanguage"] = "语音语言",
        ["TextLanguage"] = "文字语言",
        ["StatusAndPreview"] = "状态与预览",
        ["CurrentStatus"] = "当前状态",
        ["ExpectedOperation"] = "操作预览",
        ["Actions"] = "执行操作",
        ["ApplyConfiguration"] = "应用配置",
        ["RefreshStatus"] = "刷新状态",
        ["Reapply"] = "重新应用",
        ["AboutTitle"] = "关于 FH 语言组合工具",
        ["AboutProductName"] = "FH 语言组合工具",
        ["AboutDescription"] = "用于在 Steam 版 Forza Horizon 5 / 6 中组合不同的语音语言与文字语言。核心逻辑位于独立的 .NET 服务层，所有文件修改前都会创建备份。",
        ["Version"] = "版本",
        ["ProjectAddress"] = "项目地址",
        ["Ready"] = "就绪。",
        ["ConfirmReapplyTitle"] = "确认重新应用",
        ["ConfirmReapply"] = "将先恢复最近一次备份中的原始语音包，再使用更新后的文字包重新应用当前组合。是否继续？",
        ["ReapplyComplete"] = "语言组合已重新应用。",
        ["ReapplyFailed"] = "重新应用失败。",
        ["SelectGameToLoadStatus"] = "请选择游戏以加载状态。",
        ["ChooseTwoDifferentLanguages"] = "请选择两个不同的语言。",
        ["DetectingGames"] = "正在检测 Steam 游戏……",
        ["DetectedGames"] = "检测到 {0} 个游戏。",
        ["NoSteamDetected"] = "未检测到 Steam 版 Forza Horizon，请手动添加游戏目录。",
        ["SelectedGame"] = "已选择 {0}。",
        ["ScanFailed"] = "扫描语言包失败：{0}",
        ["LanguageScanFailed"] = "语言包扫描失败。",
        ["SelectGameRoot"] = "请选择游戏根目录。",
        ["SelectGameRootDialog"] = "选择 Forza Horizon 游戏根目录",
        ["ManualDirectoryTitle"] = "手动添加目录",
        ["ValidatingDirectory"] = "正在验证目录……",
        ["ManualDirectoryValidated"] = "目录验证完成。",
        ["NoReapply"] = "当前状态不需要重新应用，或没有可用的历史语言组合。",
        ["ReapplyTitle"] = "重新应用",
        ["SelectComboFirst"] = "请先选择游戏、语音语言和文字语言。",
        ["ApplyTitle"] = "应用配置",
        ["SameLanguage"] = "语音语言与文字语言不能相同。",
        ["GameRunningApply"] = "游戏正在运行，请关闭游戏后再应用配置。",
        ["ConfirmApplyTitle"] = "确认应用",
        ["ConfirmApply"] = "确定将“{0}”文字应用到“{1}”语音包吗？\n\n操作前会自动创建备份。",
        ["ApplyFailedTitle"] = "应用失败",
        ["ApplyCompleteTitle"] = "应用完成",
        ["ApplyFailed"] = "配置应用失败。",
        ["ConfigurationApplied"] = "配置已应用。",
        ["SteamLanguageUpdated"] = "Steam 游戏语言已同步更新。",
        ["GameRunningRestore"] = "游戏正在运行，请关闭游戏后再恢复备份。",
        ["RestoreTitle"] = "恢复备份",
        ["ConfirmRestoreTitle"] = "确认恢复",
        ["ConfirmRestore"] = "确定恢复 {0} 创建的备份吗？",
        ["RestoreCompleteTitle"] = "恢复完成",
        ["RestoreFailedTitle"] = "恢复失败",
        ["BackupRestored"] = "备份已恢复。",
        ["RestoreFailed"] = "备份恢复失败。",
        ["NotConfigured"] = "尚未应用语言组合。",
        ["StateApplied"] = "已应用",
        ["StateReverted"] = "已恢复",
        ["StateOutdated"] = "需要重新应用",
        ["StateModified"] = "文件已被外部修改",
        ["StateExternalSwap"] = "检测到外部双向互换",
        ["StateExternalDuplicate"] = "检测到外部文件覆盖",
        ["ExternalSwapDetail"] = "状态：{0}；语言包：{1} ↔ {2}；未发现工具备份，无法安全恢复。",
        ["ExternalDuplicateDetail"] = "状态：{0}；{1}.zip 与 {2}.zip 内容完全相同；未发现工具备份，无法确定覆盖方向。",
        ["StatusDetail"] = "状态：{0}；语音：{1}；文字：{2}；应用时间：{3}",
        ["StatusUnavailable"] = "无法读取状态：{0}",
        ["SameLanguagePreview"] = "语音语言与文字语言相同，无需执行修改。",
        ["OperationPreview"] = "将 {0} 复制并替换 {1}，替换前会备份原始 {1}。",
        ["BackupTitle"] = "语音 {0} + 文字 {1}",
        ["InvalidBackup"] = "备份无效",
        ["Language_EN"] = "英语",
        ["Language_GB"] = "英语（英国）",
        ["Language_JP"] = "日语",
        ["Language_CHS"] = "简体中文",
        ["Language_CHT"] = "繁体中文",
        ["Language_FR"] = "法语",
        ["Language_DE"] = "德语",
        ["Language_ES"] = "西班牙语",
        ["Language_MX"] = "西班牙语（墨西哥）",
        ["Language_IT"] = "意大利语",
        ["Language_PT"] = "葡萄牙语",
        ["Language_BR"] = "葡萄牙语（巴西）",
        ["Language_KO"] = "韩语",
        ["Language_RU"] = "俄语",
        ["Language_PL"] = "波兰语",
        ["Language_NL"] = "荷兰语",
        ["Language_TR"] = "土耳其语",
        ["Language_DK"] = "丹麦语",
        ["Language_SV"] = "瑞典语",
        ["Language_NO"] = "挪威语",
        ["Language_FI"] = "芬兰语",
        ["Language_CZ"] = "捷克语",
        ["Language_HU"] = "匈牙利语",
        ["Language_EL"] = "希腊语"
    };

    private static IReadOnlyDictionary<string, string> CreateEnglish() => new Dictionary<string, string>
    {
        ["AppName"] = "FH Language Combo Tool",
        ["NavHome"] = "Home",
        ["NavBackups"] = "Backups",
        ["NavSettings"] = "Settings",
        ["NavAbout"] = "About",
        ["LanguageTitle"] = "Interface Language",
        ["LanguageIntro"] = "Choose the interface language. You can change it later in Settings.",
        ["Continue"] = "Continue",
        ["DisclaimerTitle"] = "Before You Continue",
        ["DisclaimerIntro"] = "This tool modifies local Forza Horizon language resource files. Read and confirm the following before continuing.",
        ["Disclaimer1"] = "This tool is not affiliated with Playground Games, Microsoft, Xbox, or Turn 10.",
        ["Disclaimer2"] = "The tool modifies StringTables language files and creates a backup before each operation.",
        ["Disclaimer3"] = "Game updates or Steam file verification may overwrite changes, requiring the configuration to be reapplied.",
        ["Disclaimer4"] = "You accept the risks of modifying local files and confirm that the game is not running.",
        ["Accept"] = "Accept and Continue",
        ["Game"] = "Game",
        ["InstalledGames"] = "Installed Games",
        ["Detect"] = "Detect",
        ["NoGameSelected"] = "No game selected.",
        ["ManualDirectory"] = "Add Directory Manually",
        ["ManualPathHint"] = "Select the game root directory",
        ["Browse"] = "Browse",
        ["Validate"] = "Validate",
        ["Backups"] = "Backup and Restore",
        ["BackupsDescription"] = "Select a valid backup to restore the game language resources to their previous state.",
        ["RestoreSelected"] = "Restore Selected Backup",
        ["Settings"] = "Settings",
        ["InterfaceLanguage"] = "Interface Language",
        ["SettingsDescription"] = "Change the interface language or reset the first-run prompts.",
        ["ResetFirstRun"] = "Reset First-Run Prompts",
        ["LanguageCombo"] = "Language Configuration",
        ["LanguageComboIntro"] = "Choose separate voice and text languages for the game.",
        ["LanguageComboDescription"] = "The tool backs up the original voice pack before replacing it with the selected text pack.",
        ["VoiceLanguage"] = "Voice Language",
        ["TextLanguage"] = "Text Language",
        ["StatusAndPreview"] = "Status and Preview",
        ["CurrentStatus"] = "Current Status",
        ["ExpectedOperation"] = "Operation Preview",
        ["Actions"] = "Actions",
        ["ApplyConfiguration"] = "Apply Configuration",
        ["RefreshStatus"] = "Refresh Status",
        ["Reapply"] = "Reapply",
        ["AboutTitle"] = "About FH Language Combo Tool",
        ["AboutProductName"] = "FH Language Combo Tool",
        ["AboutDescription"] = "Combines different voice and text languages in the Steam versions of Forza Horizon 5 / 6. Core operations run in an independent .NET service layer, and every file change is backed up first.",
        ["Version"] = "Version",
        ["ProjectAddress"] = "Project",
        ["Ready"] = "Ready.",
        ["ConfirmReapplyTitle"] = "Confirm Reapply",
        ["ConfirmReapply"] = "The latest backup will first restore the original voice pack, then the updated text pack will be applied again. Continue?",
        ["ReapplyComplete"] = "The language combination was reapplied.",
        ["ReapplyFailed"] = "Reapply failed.",
        ["SelectGameToLoadStatus"] = "Select a game to load its status.",
        ["ChooseTwoDifferentLanguages"] = "Choose two different languages.",
        ["DetectingGames"] = "Detecting Steam games...",
        ["DetectedGames"] = "Detected {0} game(s).",
        ["NoSteamDetected"] = "No Steam Forza Horizon installation was detected. Add the game directory manually.",
        ["SelectedGame"] = "Selected {0}.",
        ["ScanFailed"] = "Language pack scan failed: {0}",
        ["LanguageScanFailed"] = "Language pack scan failed.",
        ["SelectGameRoot"] = "Select the game root directory.",
        ["SelectGameRootDialog"] = "Select the Forza Horizon game root directory",
        ["ManualDirectoryTitle"] = "Add Directory Manually",
        ["ValidatingDirectory"] = "Validating directory...",
        ["ManualDirectoryValidated"] = "Directory validation completed.",
        ["NoReapply"] = "The current state does not require reapplying, or no previous language combination is available.",
        ["ReapplyTitle"] = "Reapply",
        ["SelectComboFirst"] = "Select a game, voice language, and text language first.",
        ["ApplyTitle"] = "Apply Configuration",
        ["SameLanguage"] = "Voice and text languages must be different.",
        ["GameRunningApply"] = "The game is running. Close it before applying a configuration.",
        ["ConfirmApplyTitle"] = "Confirm Apply",
        ["ConfirmApply"] = "Apply “{0}” text to the “{1}” voice pack?\n\nA backup will be created first.",
        ["ApplyFailedTitle"] = "Apply Failed",
        ["ApplyCompleteTitle"] = "Apply Complete",
        ["ApplyFailed"] = "Configuration failed.",
        ["ConfigurationApplied"] = "Configuration applied.",
        ["SteamLanguageUpdated"] = "The Steam game language was updated.",
        ["GameRunningRestore"] = "The game is running. Close it before restoring a backup.",
        ["RestoreTitle"] = "Restore Backup",
        ["ConfirmRestoreTitle"] = "Confirm Restore",
        ["ConfirmRestore"] = "Restore the backup created at {0}?",
        ["RestoreCompleteTitle"] = "Restore Complete",
        ["RestoreFailedTitle"] = "Restore Failed",
        ["BackupRestored"] = "Backup restored.",
        ["RestoreFailed"] = "Backup restore failed.",
        ["NotConfigured"] = "No language combination has been applied.",
        ["StateApplied"] = "Applied",
        ["StateReverted"] = "Restored",
        ["StateOutdated"] = "Reapply Required",
        ["StateModified"] = "Externally Modified",
        ["StateExternalSwap"] = "External Two-Way Swap Detected",
        ["StateExternalDuplicate"] = "External File Replacement Detected",
        ["ExternalSwapDetail"] = "Status: {0}; packs: {1} ↔ {2}; no tool backup was found, so the original files cannot be restored safely.",
        ["ExternalDuplicateDetail"] = "Status: {0}; {1}.zip and {2}.zip are identical; no tool backup was found, so the replacement direction cannot be determined.",
        ["StatusDetail"] = "Status: {0}; voice: {1}; text: {2}; applied: {3}",
        ["StatusUnavailable"] = "Unable to read status: {0}",
        ["SameLanguagePreview"] = "Voice and text languages are the same; no changes are required.",
        ["OperationPreview"] = "Copy {0} over {1}, backing up the original {1} first.",
        ["BackupTitle"] = "Voice {0} + Text {1}",
        ["InvalidBackup"] = "Invalid backup",
        ["Language_EN"] = "English",
        ["Language_GB"] = "English (UK)",
        ["Language_JP"] = "Japanese",
        ["Language_CHS"] = "Simplified Chinese",
        ["Language_CHT"] = "Traditional Chinese",
        ["Language_FR"] = "French",
        ["Language_DE"] = "German",
        ["Language_ES"] = "Spanish",
        ["Language_MX"] = "Spanish (Mexico)",
        ["Language_IT"] = "Italian",
        ["Language_PT"] = "Portuguese",
        ["Language_BR"] = "Portuguese (Brazil)",
        ["Language_KO"] = "Korean",
        ["Language_RU"] = "Russian",
        ["Language_PL"] = "Polish",
        ["Language_NL"] = "Dutch",
        ["Language_TR"] = "Turkish",
        ["Language_DK"] = "Danish",
        ["Language_SV"] = "Swedish",
        ["Language_NO"] = "Norwegian",
        ["Language_FI"] = "Finnish",
        ["Language_CZ"] = "Czech",
        ["Language_HU"] = "Hungarian",
        ["Language_EL"] = "Greek"
    };
}

public sealed record UiLanguage(string Code, string DisplayName)
{
    public string Display => DisplayName;
}
